// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqQSjQxJ8LxGo7V9pT7K_6e8rHp3yN4oE',
    appId: '1:49598092873:web:abcdef1234567890123456',
    messagingSenderId: '49598092873',
    projectId: 'bottles-up-2d907',
    authDomain: 'bottles-up-2d907.firebaseapp.com',
    storageBucket: 'bottles-up-2d907.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZ2q3qOtW4DMRMdOf4eSeTWN16rIXma5w',
    appId: '1:49598092873:android:9f3f18e6cf9e345c219198',
    messagingSenderId: '49598092873',
    projectId: 'bottles-up-2d907',
    storageBucket: 'bottles-up-2d907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqQSjQxJ8LxGo7V9pT7K_6e8rHp3yN4oE',
    appId: '1:49598092873:ios:fedcba0987654321abcdef',
    messagingSenderId: '49598092873',
    projectId: 'bottles-up-2d907',
    storageBucket: 'bottles-up-2d907.appspot.com',
    iosBundleId: 'com.example.bottlesUpVendor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqQSjQxJ8LxGo7V9pT7K_6e8rHp3yN4oE',
    appId: '1:49598092873:macos:fedcba0987654321abcdef',
    messagingSenderId: '49598092873',
    projectId: 'bottles-up-2d907',
    storageBucket: 'bottles-up-2d907.appspot.com',
    iosBundleId: 'com.example.bottlesUpVendor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqQSjQxJ8LxGo7V9pT7K_6e8rHp3yN4oE',
    appId: '1:49598092873:windows:1234567890abcdef987654',
    messagingSenderId: '49598092873',
    projectId: 'bottles-up-2d907',
  );
} 